name: myenv
channels:
  - defaults
dependencies:
  - python=3.10  
  - numpy
  - pillow  # PIL is available as 'pillow'
  - openai
  - pydub
  - requests
  - sounddevice
  - tiktoken
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.12
  - pip=23.3.1
  - python=3.10
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
    - elevenlabs   # Add any library that is unavailable in with conda install
    - cffi==1.16.0
    - pycparser==2.21
    - pydub==0.25.1
    - sounddevice==0.4.6
